// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoHL_2YGimX_praP1AL9JbCOBpAPzZUfI',
    appId: '1:85073627465:web:860363f405fb1151147298',
    messagingSenderId: '85073627465',
    projectId: 'medadhere-189f9',
    authDomain: 'medadhere-189f9.firebaseapp.com',
    storageBucket: 'medadhere-189f9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyG_OpQRYWcgCiGQmFL8Y2lTWT-QhERxM',
    appId: '1:85073627465:android:6d7fa56a4ddcf0fb147298',
    messagingSenderId: '85073627465',
    projectId: 'medadhere-189f9',
    storageBucket: 'medadhere-189f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC-rmk74zNX9QvGf0_fcYiM2xsq4U7j5E',
    appId: '1:85073627465:ios:d95079941f08aa7a147298',
    messagingSenderId: '85073627465',
    projectId: 'medadhere-189f9',
    storageBucket: 'medadhere-189f9.firebasestorage.app',
    androidClientId: '85073627465-55bg38i6a4s745t7dc70nq4ai5jkvtnv.apps.googleusercontent.com',
    iosClientId: '85073627465-4j5pqv1smnrtrm4ngte53sjb49qkbrb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.medadhere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC-rmk74zNX9QvGf0_fcYiM2xsq4U7j5E',
    appId: '1:85073627465:ios:d95079941f08aa7a147298',
    messagingSenderId: '85073627465',
    projectId: 'medadhere-189f9',
    storageBucket: 'medadhere-189f9.firebasestorage.app',
    androidClientId: '85073627465-55bg38i6a4s745t7dc70nq4ai5jkvtnv.apps.googleusercontent.com',
    iosClientId: '85073627465-4j5pqv1smnrtrm4ngte53sjb49qkbrb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.medadhere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoHL_2YGimX_praP1AL9JbCOBpAPzZUfI',
    appId: '1:85073627465:web:b2976608ed9e06bb147298',
    messagingSenderId: '85073627465',
    projectId: 'medadhere-189f9',
    authDomain: 'medadhere-189f9.firebaseapp.com',
    storageBucket: 'medadhere-189f9.firebasestorage.app',
  );
}
